### ISSUE TITLE
Accepts outside drag events

### ISSUE THREAD

**Issue by Georgette** [danielstocks/react-sortable#11]
Go to your demo, then click and drag a file off your desk top and hover it over the demo block. You will notice that the blocks will rearrange as the module doesn't restrict drag events from external sources.

**Comment by honkskillet** [comment]
Yeah.  I tested this out on safari and it wasn't a problem but then I opened up chrome and it acts as @Georgette states.

There are also a lot of issue with elements being restricted from spots they should be able to be dropped in.  Mostly at the end of a subarray.  I worked on nester sortable UITableView (iOS version of a list) a while ago and I know the logic gets a little ugly.  It would be great to see this project carried on to a useable state.

**Comment by Dharmoslap** [comment]
This is an issue of browser implementation. We can't do anything about it here.
