### ISSUE TITLE
npm module does not export anything

### ISSUE THREAD

**Issue by stefanfisk** [danielstocks/react-sortable#12]
The module is currently not directly usable via webpack (possibly also not browserify) since the module does not export anything. Shimming works for now, but of course it adds complexity.

**Comment by tomatau** [comment]
Literally just hit exactly the same problem

**Comment by stefanfisk** [comment]
If you're in webpack install exports-loader and use `require('exports?Sortable!react-sortable')`.

**Comment by tomatau** [comment]
adds complication to my test process - would rather not have an edge case for just one library. Thanks though :) Just copied the source as it's only a small file.

**Comment by Dharmoslap** [comment]
fixed in 0549012
