### ISSUE TITLE
Doesn't work with React 0.12.2

### ISSUE THREAD

**Issue by stefanfisk** [danielstocks/react-sortable#13]
Since `getDefaultProps()` is now called by `React.createClass()`, and `Sortable.getDefaultProps()` tries to access `this` as if it was an element instance everything breaks miserably :(

**Comment by tomatau** [comment]
Exactly the same problem here too! :D Should be using component lifecycle events and managing it's own state, not working from default props - that's for the component itself.

**Comment by fpayer** [comment]
Anyone have a fix for this?

**Comment by tomatau** [comment]
https://github.com/RubaXa/Sortable/blob/master/react-sortable-mixin.js

**Comment by Dharmoslap** [comment]
current version works with react 0.14
