### ISSUE TITLE
Cannot drag below the fold

### ISSUE THREAD

**Issue by tonym** [danielstocks/react-sortable#20]
Dragging below the fold selects content, and misplaces the mouse

Steps to reproduce
Create a list that is longer than the page
Drag an item below the bottom of the page
Notice how the page content is selected, and the mouse no longer is on the dragged item, and the dragged item has jumped up on the page

Expected behavior
The page scrolls when the item is dragged below the fold, and the mouse stays on the dragged item

**Comment by Dharmoslap** [comment]
That happens just for nested example, right?
