### ISSUE TITLE
Can't scroll list while dragging item

### ISSUE THREAD

**Issue by bgnorlov** [danielstocks/react-sortable#21]
I have "overflow:auto" property on ul-list with long set of items. I tried to scroll list after I pressing mouse button to drag item but I can't! In this example http://webcloud.se/react-sortable/nested.html just set overflow: auto property and fixed height (for example 200px) and you can reproduce this bug in chrome.

**Comment by Dharmoslap** [comment]
Could you record a gif for this issue? I had no problem with scrolling so far.

**Comment by skitterm** [comment]
I saw the same issue with the gridItems example (set list height 250px, overflow auto). It worked fine for me on Windows, but on Mac Safari I couldn't scroll down when I have a dragged item. Without dragging an item I could scroll.

**Comment by Dharmoslap** [comment]
Seems like this is an issue of browser itself.
