### ISSUE TITLE
React 15 support

### ISSUE THREAD

**Issue by jamezor** [danielstocks/react-sortable#24]
Just wondering if/when React 15 might be supported by your fine component? Thanks!

**Comment by Dharmoslap** [comment]
There should't be any compatibility after updating to React 15. If you will find one, please report it here.
I'm planning to switch to React 15 in a couple of days.

**Comment by Dharmoslap** [comment]
Alright, React 15 is now in supported. :]

**Comment by jamezor** [comment]
Awesome, thank you!
