### ISSUE TITLE
Stable branch?

### ISSUE THREAD

**Issue by rpastorelle** [danielstocks/react-sortable#25]
Is there a stable branch of release? I would love to use this but the NPM version is unusable. And it looks like the master branch is in flux.

**Comment by Dharmoslap** [comment]
There will be stable branch for Gridlist outline today. Nested one will take a bit more work.

**Comment by rpastorelle** [comment]
Thanks! I have a really cool & simple use-case for it. Can't wait for the new hotness 🔥

**Comment by rpastorelle** [comment]
Can't really get it working. I will just wait until it's more stable.

**Comment by Dharmoslap** [comment]
release in npm is not updated

**Comment by Dharmoslap** [comment]
in package.json you can try to use 
"react-sortable": "https://github.com/danielstocks/react-sortable/tarball/v1.0-gridlist"
