### ISSUE TITLE
html tables support

### ISSUE THREAD

**Issue by degr** [danielstocks/react-sortable#28]
Not work in case of use with 'th', 'td', 'tr' tags, because 'div' can't be used inside of any 'table', 'tbody', 'tr' tags. So, when you wrap your component with <div className={this.isDragging() ? draggingClassName : ""}> it fail.

**Comment by Dharmoslap** [comment]
Taking look at this one.

**Comment by degr** [comment]
I implement dnd for my tables by self (it take around 50 rows of code, with html5 dnd attributes). So, I will no check it. But anyway, thanks.

**Comment by Dharmoslap** [comment]
Alright, you would be also very much welcomed to make a PR into this repository.

**Comment by degr** [comment]
In your case better do this:

`export function SortableComposition(Component, wrapperTagName) {`
...
`return (
          React.createElement(wrapperTagName || 'div', {className:this.isDragging() ? draggingClassName : "}, <Component {...this.props} ...`

Using this trick this component will be more scalable, and you will be able to use it inside of
table, dl, li, ul, span and other non-block tags

**Comment by Dharmoslap** [comment]
Fixed in current master https://github.com/danielstocks/react-sortable#changing-the-wrapping-tag
