### ISSUE TITLE
How to make this work with webpack?

### ISSUE THREAD

**Issue by jfrolich** [danielstocks/react-sortable#29]
the index.js contains es6 code. Webpack does not seem to compile that down by default for npm modules. How to use this package?

**Comment by Dharmoslap** [comment]
You can see it directly in in the repository: https://github.com/danielstocks/react-sortable/blob/master/webpack.config.js.
Using babel-loader should work.

**Comment by Dharmoslap** [comment]
Now I'm taking one more look at it.

**Comment by Dharmoslap** [comment]
I updated build system to webpack 2.
If you don't want to use webpack 2, you can use already compiled and minified version of library at "build/index_bundle.js".
