### ISSUE TITLE
import {Sortable} from 'react-sortable', Sortable is undefined

### ISSUE THREAD

**Issue by wodog** [danielstocks/react-sortable#38]
I follow the **Example Implementation** in the README.md

the import {Sortable} from 'react-sortable' can't work
but try import Sortable from 'react-sortable' can work

**Comment by ahutchings** [comment]
The code in master is not yet published to npm. If you installed from npm, take a look at the readme for the 1.0 tag: https://github.com/danielstocks/react-sortable/tree/v1.0

**Comment by tnrich** [comment]
Hey @ahutchings 
When will the code in master be pushed to npm?

Thanks!

**Comment by Dharmoslap** [comment]
Hi @tnrich,
unfortunately I don't have rights to publish to npm.
It can be done only by @danielstocks.
Nevertheless if you want to install code from master you can always do it like it's here: https://github.com/danielstocks/react-sortable/blob/master/demo/package.json
I hope that the owner of npm repo can publish changes soon, or even better if he would provide me rights to do that.

**Comment by danielstocks** [comment]
@tnrich @Dharmoslap 
Fixed. Sorry for the delay
https://www.npmjs.com/package/react-sortable
