### ISSUE TITLE
Container div prevents using sortable for table rows

### ISSUE THREAD

**Issue by ahutchings** [danielstocks/react-sortable#41]
Because sortable wraps the decorated component with a `<div>` element, sortable cannot be used for table rows or list items. We've fixed this in our project by modifying react-sortable to render the decorated component directly as the root component with no containing element. This requires that the wrapped component be aware of and render the props generated by sortable. In our case, the wrapped component uses the object spread syntax to ensure all sortable-generated props are rendered.

```javascript
<tr {...this.props} />
```

We're open to better alternatives, since I understand this pattern leads to new "unknown props" warnings in 0.15.2. https://facebook.github.io/react/warnings/unknown-prop.html

Any ideas?

cc @ryanswanson

**Comment by Dharmoslap** [comment]
Fixed in current master https://github.com/danielstocks/react-sortable#changing-the-wrapping-tag

**Comment by ahutchings** [comment]
That strategy fixes the issue for list items, but I'm not sure how to use it with table rows. The wrapped component is rendered as the immediate child of sortable, but in the case of table rows children needs to be an array of td or td components, not a single component.

**Comment by Dharmoslap** [comment]
I see, and what would you suggest?

**Comment by Dharmoslap** [comment]
Alright, I did another refactoring. You can find working table in https://github.com/danielstocks/react-sortable/tree/master/example-table.

**Comment by ahutchings** [comment]
Thanks, that should work for us. Closing this issue.
