### ISSUE TITLE
Some thoughts on this

### ISSUE THREAD

**Issue by nicolas-goudry** [danielstocks/react-sortable#48]
Would like to share some enhancements ideas about this:
1. Allow to add custom className to items
2. Don't sort while dragEnd didn't happened
3. Cancel sort on ESC key press

If you're ok, I can fork and work on it :smiley:

**Comment by Dharmoslap** [comment]
Sounds very cool, you can create PR for this. I think 2 might not be that desirable, as how it is working now it is giving you an immediate feedback..

**Comment by Dharmoslap** [comment]
No progress so far? I could also start with this later.

**Comment by nicolas-goudry** [comment]
Hey, sorry for my absence on this subject…

I’m currently on vacation but I think I did some work on this at work.

Will keep you updated next monday!
