### ISSUE TITLE
hoc should be lowercase.

### ISSUE THREAD

**Issue by bentatum** [danielstocks/react-sortable#49]
`sortable(ListItem)`

...so folks don't confuse it with a regular component

`<Sortable><ListItem/></Sortable>`

**Comment by Dharmoslap** [comment]
It's there now.

**Comment by maackle** [comment]
This is a breaking change that got applied to a minor version update, which violates semver. I think the right thing to do would have been to keep the original uppercase `Sortable` as a deprecated alias until 2.0. We just had our build break because of this. Not a big deal, but just FYI.
