### ISSUE TITLE
Sortable not working in firefox

### ISSUE THREAD

**Issue by stefanomiccoli** [danielstocks/react-sortable#56]
Hi everybody.

We are using react-sortable in the admin UI of a project.
The client reports that tool is unusable in firefox (>=49.0.0 both win and linux). After sortEnd it always redirect the browser to about:blank.
I'm still looking at the code to determine the cause, but it is visible also on official demos here http://webcloud.se/react-sortable/

How to reproduce:

1. Go to http://webcloud.se/react-sortable/ with FF
2. reorder an item in the list
3. you are being redirected to about:blank

Strange thing is that if you try to drag an item outside the list (either as first or last element), sorting works well.

As soon as I find the problem (and if im able to fix it) I will fork and submit a merge request.

Cheers,
Stefano

**Comment by Dharmoslap** [comment]
I can see, this is possible to fix by setting an onDrop callback that will call preventDefault() function.

Like this:

```
 <Component
          ....
          onDragOver={this.dragOver}
          onDragStart={this.sortStart}
          onDragEnd={this.sortEnd}
          onDrop={function(e){e.preventDefault();}}
           ....
          />
```

I have already pushed a fix to master branch, I will release it at some point today.

**Comment by stefanomiccoli** [comment]
it seems to be related to this: http://stackoverflow.com/questions/14541775/html5-drag-and-drop-firefox-is-being-redirected

**Comment by stefanomiccoli** [comment]
Nice, I was looking at the wrong point (onDragEnd) and it didnt work.

Thank you!
