### ISSUE TITLE
Sortable is not a function

### ISSUE THREAD

**Issue by janstuemmel** [danielstocks/react-sortable#57]
Since realese 1.2.0 i have following issue:

```
Uncaught TypeError: Sortable is not a function(…)
```

my setup:

```js
...
var Sortable = require('react-sortable').Sortable;
...
var SortableImageItem = Sortable(ImageItem); // <- chrome debugger error
```

**Comment by janstuemmel** [comment]
ahh you changed the function to lowercase!

this i sa bit problematic because the most of the guys have in their package.json something like `"react-sortable": "^1.1.0"`, maybe you can provide an alias function or something like that and make a patch release...

**Comment by Dharmoslap** [comment]
I forgot to mention this in the release notes. Now you can see it there, as well as in the README file.

**Comment by Dharmoslap** [comment]
If you would like to, you are welcome to make a PR for compatibly patch.

**Comment by janstuemmel** [comment]
isnt it just `echo "export { SortableComposition as sortable } from './SortableComposition'" >> src/index.js;` 

i can pull request that if you want?
