### ISSUE TITLE
Why call updateState while dragging?

### ISSUE THREAD

**Issue by astanciu** [danielstocks/react-sortable#59]
Is it really necessary to call updateState **while** dragging, rather than simply at the end? If so can we get another method that is called once the drag is done? I'd rather not push the state back up the chain while the operation is in progress, this kicks off a flood of events.

**Comment by Dharmoslap** [comment]
Sounds reasonable, but you still need to tell the component to trigger the render function when the two items are swapped. I very like the idea of using two separate methods instead of one, you are welcome to contribute on this and create PR.

**Comment by springuper** [comment]
+1
