### ISSUE TITLE
Half of item not droppable

### ISSUE THREAD

**Issue by edamtoft** [danielstocks/react-sortable#64]
On the example, it looks like half of each item does not respond when an item is dragged over.

http://webcloud.se/react-sortable/

![image](https://cloud.githubusercontent.com/assets/6130842/20842025/ff4b85ec-b883-11e6-9b23-f047b15adc3a.png)

In the source, it calls isMouseBeyond, which seems to be the source of this behavior
```javascript
export function isMouseBeyond(mousePos, elementPos, elementSize) { //TODO refactor for UP
  var breakPoint = elementSize / 2; //break point is set to the middle line of element
  var mouseOverlap = mousePos - elementPos;
  return mouseOverlap > breakPoint;
}
```

it worked as expected and everything was droppable when breakPoint was just set to zero. I assume that the breakpoint is in there for a reason, but maybe we could at least add something to disable it with a prop? Wanted to get thoughts on best way to address that since there's already a TODO there. I'd be happy to send you a PR.

**Comment by tkaetzel** [comment]
Further, in the list functionality, it's the top half that is unresponsive, which is debatably more problematic.

**Comment by ndugger** [comment]
I get this bug in my usage as well.

**Comment by Dharmoslap** [comment]
Fixed
