### ISSUE TITLE
How to set displayName in ES6 Class?

### ISSUE THREAD

**Issue by Petercopter** [danielstocks/react-sortable#65]
I can't seem to get the `displayName` set, so I'm seeing
```
<No display name></No display name>
```
in the DOM. I've tried in the constructor, after the class... nothing seems to work.

**Comment by Dharmoslap** [comment]
Hi, how can I replicate this?

**Comment by you-fail-me** [comment]
@Dharmoslap Just create a ES2015 class component and call `Sortable` on it. Looks like it became broken at some moment, earlier worked nice for me with classes, but is broken now. Btw, it's kinda weird to support `createClass` and have issues with modern syntax nowadays :/

**Comment by Dharmoslap** [comment]
Fixed in 1.3.0
