### ISSUE TITLE
Drag elements in Firefox, it will be opened in  new tab?

### ISSUE THREAD

**Issue by 823844596** [danielstocks/react-sortable#66]
hi, i use the demo in my code, and i found one problem in Firefox, if i drag element by mouse, it will open a new tab in Firefox. how can i solve the problem? thanks~

**Comment by Dharmoslap** [comment]
Hi, are you using a current version? And which demo do you mean?

**Comment by 823844596** [comment]
hi, i use 1.2.0 version of the demo, and  if i open the demo in Firefox, it will open a new tab, and also, you can open the example url "http://webcloud.se/react-sortable"  in Firefox, and drag elements, you will see the problem. maybe Html5 drag should stop Event bubbling or do otherThing in Firefox?

**Comment by Dharmoslap** [comment]
The demo was not updated for some time, I updated it now. This bug was fixed some time ago.

**Comment by harekuer** [comment]
still exist, version 2.0.0
