### ISSUE TITLE
Disable dragging based on state

### ISSUE THREAD

**Issue by ultimagriever** [danielstocks/react-sortable#67]
Is there an option where I can say that a component cannot be dragged according to a piece of state? The documentation doesn't say anything and I am having trouble selecting text inside a sortable component.

**Comment by Dharmoslap** [comment]
You can handle this on your side, try something like this:
render: function() {
  
    var listItems = this.state.data.items.map(function(item, i) {
      if(yourCondition){
        return (
          <SortableListItem>{item}</SortableListItem>
        );
      } else {
        return item
      }
    }, this);

    return (
          <div className="list">{listItems}</div>
    )
  }

**Comment by ultimagriever** [comment]
I wound up doing something like that, instead I just passed the `draggable` property as `false` under `childProps` and it worked. Since the draggable prop was dependent on the application state, I preferred doing that instead of chucking an if-else block in my code.

So I did something like this:

```
render () {
  return (
    <SortableListItem {...props} childProps={{ draggable: this.state.draggable }}>{item}</SortableListItem>
  );
}
```
