### ISSUE TITLE
Drop-zone behavior vs. immediate reordering

### ISSUE THREAD

**Issue by amywieliczka** [danielstocks/react-sortable#71]
I've been looking at react-sortable vs. react-dnd and I'm curious about the 'drop-zone' style behavior of simple sort in the react-dnd example (http://react-dnd.github.io/react-dnd/examples-sortable-simple.html) vs. the immediate reordering in the react-sortable example. Is it possible to get this drop-zone style behavior in react-sortable? When I click 'gold', for example, I want the div to follow my mouse, and a blank space to open up in the list at the place where the 'gold' item would be inserted on drop. Should I just use react-dnd for this? 

Thanks!

**Comment by ladas-larry** [comment]
You can use react-dnd I guess.
