### ISSUE TITLE
Change default cursor 

### ISSUE THREAD

**Issue by danielravina** [danielstocks/react-sortable#75]
Hi! Is it possible to change the default cursor:
<img width="481" alt="screen shot 2017-05-15 at 7 28 50 pm" src="https://cloud.githubusercontent.com/assets/3150871/26087305/d7805dd8-39a4-11e7-94be-8198fc0fc010.png">

I tried so many ways, both with `js` and `css` and couldn't get it to change. I'm using Chrome.

Thanks

**Comment by danielstocks** [comment]
Maybe this will hep you?

http://stackoverflow.com/questions/10119514/html5-drag-drop-change-icon-cursor-while-dragging
