### ISSUE TITLE
Drag handles

### ISSUE THREAD

**Issue by andreasvirkus** [danielstocks/react-sortable#77]
My question is a simple one - is it possible to use only a certain child element as the drag handle? For example, only drag when an icon inside the draggable element is clicked?

I know I can set `{draggable: false}` to disable it for all child elements, but is it then possible to re-enable it for a certain element?

An example can be seen from `react-draggable`'s demo page
http://mzabriskie.github.io/react-draggable/example/

**Comment by Dharmoslap** [comment]
You would need to fork this repo and modify code to make, this happen. This functionality in not implemented.
