### ISSUE TITLE
Upgrade for React 16

### ISSUE THREAD

**Issue by alnorris** [danielstocks/react-sortable#81]
I'm getting

`SortableComposition.js?9396:57 Uncaught TypeError: Cannot read property 'array' of undefined
    at SortableComposition (SortableComposition.js?9396:57)
    at eval (sortableList.js?8a2a:26)
    at Object.<anonymous> (client.js:9597)
    at __webpack_require__ (client.js:670)`

**Comment by albertkim** [comment]
This library looks like it is unmaintained. For anyone reading this, DON'T USE THIS LIBRARY. The ease of use in its API is amazing, but it's not worth using if unmaintained, especially as the React ecosystem moved forward. I'm personally still looking for an alternative.

**Comment by Dharmoslap** [comment]
Fixed in 1.3.0
